[package]
name = "yaourt"
version = "1.1.0"
license = "MIT"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "3.0.0"
fuzzy-matcher = "0.3.7"
ssh-key = "0.6.7"
